# Problem 1
# Multiples of 3 and 5
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

sum = 0 

(0...1000).each do |num|
  if num % 3 == 0 || num % 5 == 0
    sum += num
  end
end

# Problem 2
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#   find the sum of the even-valued terms.

# Fibonacci with all numbers

def fib (n)
  return 0 if n == 0

  x = 0
  y = 1

  (1..n).each do
    z = (x + y)
    x = y
    y = z
  end

  return y
end

(0..15).map do |n| 
  fib(n) 
end

# Fibonacci with even numbers

fib = Enumerator.new do |y|
  a = b = 1
  loop do
    y << a
    a, b = b, a + b
  end
end

fib.take_while{|i| i < 4000000}
    .select{|x| x.even?}
    .inject(:+)


# Problem 3
# Largest prime factor
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143 ?

def isPrime candidate
  for i in 2..candidate/2
    isPrimeFactor = true
    if (candidate%i == 0)
      isPrimeFactor = false
      break;
    end
  end
  return isPrimeFactor
end

num = 600851475143
limit = num / 2
possibleFactor = 2
factors = []
maxFactorFound = false
while (possibleFactor < limit && !maxFactorFound)
  if ((num  % possibleFactor) == 0)
    quotient = num / possibleFactor;
    if (isPrime(quotient))
      maxFactor = quotient;
      maxFactorFound = true;
    end
    factors.push possibleFactor
    limit = quotient
  end
  possibleFactor += 1
end
if (!maxFactorFound)
  factors = factors.reverse
  factors.each { |factor|
    if (isPrime(factor))
      maxFactor = factor
      break
    end
  }
end
puts "Max factor for #{num} is #{maxFactor}"







